name = 'John Sperger'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Typography-forward minimalist theme. Font scaling for dark and light mode to account for optical differences. Uses open-type font features'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'personal', 'academic', 'light', 'dark', 'minimal']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'John Sperger'
  homepage = 'https://www.jsperger.com'

# If porting an existing theme
[original]
  author = "Athul Cyriac Ajay"
  homepage = "https://github.com/athul"
  repo = "https://github.com/athul/archie"
